# Generated by Django 5.0.4 on 2024-06-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Фамилия и имя')),
                ('company', models.CharField(blank=True, max_length=64, null=True, verbose_name='Компания')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('check_politic', models.BooleanField(verbose_name='')),
            ],
        ),
    ]
