# Generated by Django 5.0.4 on 2024-06-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='email',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='phone_number',
            field=models.CharField(max_length=64, verbose_name='Номер телефона'),
        ),
    ]
